name: bitsgap
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  connectivity: ^3.0.6
  provider: ^6.0.5
  validators2: ^4.0.0
  url_launcher: ^6.1.10
  http: ^0.13.5
  flutter_svg: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/svg/Logo.svg
    - assets/svg/Head.svg

  fonts:
    - family: TT Norms Pro
      fonts:
        - asset: assets/fonts/tt_norms_pro/TTNormsPro-Regular.ttf
        - asset: assets/fonts/tt_norms_pro/TTNormsPro-Italic.ttf
          style: italic
        - asset: assets/fonts/tt_norms_pro/TTNormsPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/tt_norms_pro/TTNormsPro-Medium.ttf
          weight: 500


